### PR TITLE
DEV-338 new options and type

### PR DESCRIPTION
**Pull request by hhagelbe**

### CODE REVIEW

**Comment by dabio** [comment]
Why aren't we using options instead of the new field `types`?

**Comment by hhagelbe** [comment]
Options are a bit different than types.. You can have only one type, but multiple options.

**Comment by dabio** [comment]
I don't see a problem with that. Even when one parking space has one type. It matters what the client does with it.

**Comment by dabio** [comment]
👍

**Comment by christiangoltz** [comment]
:+1:

**Pull request merged**
